name: json format test

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: sudo apt-get install jq
  
    - name: Test format
      run: jq . list.json
